alias ls='ls --color=auto'
alias ll='ls -l'
alias la='ls -A'
alias lla='ls -lA'
alias l='ls -CF'
alias gi='git'
alias g='git'
alias tu='tar zxvf'
alias v='vim --remote-silent'
alias rb='ruby'
alias cdw='cd /w/WEBSERVER'
alias irb='irb --noreadline'
alias dvagrant='VAGRANT_LOG=info vagrant'
alias propelall="php symfony propel:build-model && php symfony propel:build-form && php symfony propel:build-filter && php symfony propel:build-sql"
alias propelfdb="propelall && php symfony propel:insert-sql --env=dev --no-confirmation && php symfony propel:data-load --env=dev"
